server {
    listen 80;

    # Rota pública de Login -> Envia para a Lambda de Auth
    location /auth {
        proxy_pass http://auth-lambda:3000/auth;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Rotas protegidas da API -> Envia para a Aplicação Laravel
    location /api/ {
        proxy_pass http://app:80/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}