server {
    listen 80;
    server_name localhost;

    # Cabeçalhos globais para responder CORS ao Swagger
    add_header 'Access-Control-Allow-Origin' '*' always;
    add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, PATCH, DELETE, OPTIONS' always;
    add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, Accept, X-Trace-Id' always;

    # Resposta rápida de Preflight (OPTIONS)
    if ($request_method = 'OPTIONS') {
        return 204;
    }

    # 1. Redireciona a Autenticação por CPF para o container da Lambda
    location /auth {
        proxy_pass http://auth-lambda:3000/auth;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 2. Redireciona todas as rotas da API e Documentação para o Laravel
    location / {
        proxy_pass http://app:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}