name: Deploy Laravel App to K3s

on:
  push:
    branches: [ master ]

# ADICIONE ESTE BLOCO DE PERMISSÕES
permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata (Tags/Labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy App on K3s via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 5m
          script: |
            # 1. Cria a Secret de autenticação para o GHCR (caso o repositório seja privado)
            sudo k3s kubectl create secret docker-registry ghcr-secret \
              --docker-server=ghcr.io \
              --docker-username=william-moura \
              --docker-password=${{ secrets.GITHUB_TOKEN }} \
              --namespace=default --dry-run=client -o yaml | sudo k3s kubectl apply -f -

            # 2. Atualiza a imagem e reinicia
            sudo k3s kubectl set image deployment/tc-app-laravel laravel=ghcr.io/william-moura/tech-challenge:master --namespace=default
            sudo k3s kubectl rollout restart deployment/tc-app-laravel

            # 3. Aguarda o Rollout com timeout de 45 segundos
            if ! sudo k3s kubectl rollout status deployment/tc-app-laravel --timeout=45s; then
              echo "=== DEPLOYMENT FALHOU OU DEMOROU DEMAIS ==="
              echo "--- Status dos Pods ---"
              sudo k3s kubectl get pods
              echo "--- Descreva o Pod ---"
              sudo k3s kubectl describe pods -l app=tc-app-laravel
              echo "--- Logs do Container ---"
              sudo k3s kubectl logs -l app=tc-app-laravel --tail=50
              exit 1
            fi

            # 4. Executa as Migrations se o Pod estiver saudável
            POD_NAME=$(sudo k3s kubectl get pods -l app=tc-app-laravel -o jsonpath="{.items[0].metadata.name}")
            if [ -n "$POD_NAME" ]; then
              sudo k3s kubectl exec $POD_NAME -c laravel -- php artisan migrate --force
            fi